
#  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—  â–ˆâ–ˆâ•—â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— 
#  â–ˆâ–ˆâ•”â•â•â•â•â•â•šâ•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—
#  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•
#  â•šâ•â•â•â•â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â•šâ•â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â•â• 
#  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘     
#  â•šâ•â•â•â•â•â•â•   â•šâ•â•   â•šâ•â•  â•šâ•â•â•šâ•â•  â•šâ•â•â•šâ•â•â•â•â•â•â•â•šâ•â•  â•šâ•â•â•šâ•â•â•šâ•â•     

# USER-NAME STYLE                                                
[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

# HOST-NAME STYLE
[hostname]
ssh_only = false
format = 'on [$hostname](bold purple) '
trim_at = "."
disabled = false

# REPLACE THE "â¯" SYMBOL IN THE PROMPT WITH "âœ"
[character]                            
success_symbol = "[âœ](bold green)"     
error_symbol = "[âœ](bold red)"

# DIRECTORY STYLE
[directory]
read_only = " ó°Œ¾"
read_only_style = "red"
truncation_length = 10
truncate_to_repo = true 			   
style = "bold italic blue"

# COMMAND DURATION STYLE
[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"

# MEMORY USAGE STYLE
[memory_usage]
disabled = true

[aws]
symbol = "ğŸ…° "

[azure]
symbol = "ïŒ "

[buf]
symbol = "ğŸ¦¬ "

[conda]
symbol = "î‰³ "

[container]
symbol = "ó±¡ "

[dart]
symbol = "ó°»‚ "

[docker_context]
symbol = "ïŒˆ "
format = "via [$symbol$context]($style) "
style = "blue bold"

[dotnet]
symbol = "î‰± "
style = "green"
heuristic = false

[elixir]
symbol = "ó°š¤ "

[elm]
symbol = "î‰¶ "

[git_branch]
symbol = "ï‚› "
ignore_branches = ['master', 'main']

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](green)" 
modified = "[${count}+](yellow)" 
deleted =  "[${count}-](red)" 
conflicted =  "[${count}~](red)" 
ahead = "â‡¡${count}"
behind = "â‡£${count}"
untracked = "[${count}?](blue)" 
staged = "[${count}+](green)" 

[git_state]
style =	"bold red"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "rebase"
merge = "merge"	
revert = "revert"	
cherry_pick = "cherry"
bisect = "bisect"	
am = "am"	
am_or_rebase = "am/rebase"

[golang]
symbol = "î‰› "

[haskell]
symbol = "î™¤ "

[hg_branch]
symbol = "ğŸŒ± "

[java]
symbol = "ó°¥š "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "îŠŒ "

[meson]
symbol = "î™¬ "

[nim]
symbol = "ğŸ£ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "ó°™ "

[package]
symbol = "ó°– "

[perl]
symbol = "ïˆ "

[php]
symbol = "î˜ˆ "

[python]
symbol = "îœ¼ "

[red]
symbol = "ïŒ– "

[ruby]
symbol = "î‘ "

[rust]
symbol = "ï‡ "

[scala]
symbol = "ó°““ "

[shlvl]
symbol = "îŠ£ "

[swift]
symbol = "ó° ³ "
